sudo: required

language: bash

services:
  - docker

before_install:
  - docker-compose -v

install:
  - docker-compose up -d mysql # boot mysql now to be ready when tests are started
  # download Snowflake drivers
  - >-
   docker
   run
   -e AWS_ACCESS_KEY_ID
   -e AWS_SECRET_ACCESS_KEY
   -v `pwd`:/code
   quay.io/keboola/aws-cli
   s3 cp s3://keboola-configs/drivers/snowflake/snowflake-odbc-2.14.0.x86_64.deb /code/snowflake-odbc.deb
  - docker-compose build tests
  - docker-compose run --rm tests php ./tests/loadS3.php

script:
 - docker-compose run --rm tests ./vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .
 - docker-compose run --rm tests php ./vendor/bin/phpunit tests/Mysql
 - docker-compose run --rm tests php ./vendor/bin/phpunit tests/Redshift
 - docker-compose run --rm -e REDSHIFT_LEGACY_IMPORT=1 tests php ./vendor/bin/phpunit tests/Redshift
 - docker-compose run --rm tests php ./vendor/bin/phpunit tests/Snowflake
