sudo: required

language: bash

services:
  - docker

before_install:
  - docker-compose -v

install:
  - docker-compose up -d mysql # boot mysql now to be ready when tests are started
  # download Snowflake drivers
  - >-
   docker
   run
   -e AWS_ACCESS_KEY_ID
   -e AWS_SECRET_ACCESS_KEY
   -v `pwd`:/code
   quay.io/keboola/aws-cli
   s3 cp s3://keboola-configs/drivers/snowflake/snowflake-odbc-2.14.0.x86_64.deb /code/snowflake-odbc.deb
  - docker-compose build tests

script:
 - docker-compose run --rm tests composer ci
