export REDSHIFT_HOST=
export REDSHIFT_PORT=5439
export REDSHIFT_USER=
export REDSHIFT_DATABASE=
export REDSHIFT_PASSWORD=

export SNOWFLAKE_HOST=
export SNOWFLAKE_USER=
export SNOWFLAKE_PASSWORD=
export SNOWFLAKE_DATABASE=
export SNOWFLAKE_WAREHOUSE=

export AWS_ACCESS_KEY=
export AWS_SECRET_KEY=
export AWS_S3_BUCKET=
export AWS_REGION=